server:
  port: 8762

spring:
  application:
    name: eureka-server
  security:
    user:
      name: root
      password: 123456

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka/